
Automobile Data Set
This data set consists of three types of entities: (a) the specification of an auto in terms of various characteristics, (b) its assigned insurance risk rating, (c) its normalized losses in use as compared to other cars. The second rating corresponds to the degree to which the auto is more risky than its price indicates. Cars are initially assigned a risk factor symbol associated with its price. Then, if it is more risky (or less), this symbol is adjusted by moving it up (or down) the scale. Actuarians call this process "symboling". A value of +3 indicates that the auto is risky, -3 that it is probably pretty safe.

The third factor is the relative average loss payment per insured vehicle year. This value is normalized for all autos within a particular size classification (two-door small, station wagons, sports/speciality, etc...), and represents the average loss per car per year.

Note: Several of the attributes in the database could be used as a "class" attribute.


https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data

In [138]:
import pandas as pd
import numpy as np
import seaborn as sns
from scipy.io import arff
#import scikit-learn as sklearn
from sklearn.linear_model import LinearRegression

In [139]:
raw_df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data",header=None)

In [140]:
raw_df.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [141]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
0     205 non-null int64
1     205 non-null object
2     205 non-null object
3     205 non-null object
4     205 non-null object
5     205 non-null object
6     205 non-null object
7     205 non-null object
8     205 non-null object
9     205 non-null float64
10    205 non-null float64
11    205 non-null float64
12    205 non-null float64
13    205 non-null int64
14    205 non-null object
15    205 non-null object
16    205 non-null int64
17    205 non-null object
18    205 non-null object
19    205 non-null object
20    205 non-null float64
21    205 non-null object
22    205 non-null object
23    205 non-null int64
24    205 non-null int64
25    205 non-null object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [142]:
raw_df.describe()

,0,9,10,11,12,13,16,20,23,24
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [143]:
col_names= ["symboling","normalized-losses", "make", "fuel-type", "aspiration" , "num-of-doors", "body-style", "drive-wheels", "engine-location", "wheel-base", "length", "width", "height", "curb-weight", "engine-type", "num-of-cylinders", "engine-size", "fuel-system", "bore", "stroke", "compression-ratio", "horsepower","peak-rpm","city-mpg", "highway-mpg","price"]
raw_df.columns= col_names

In [144]:
raw_df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [145]:
raw_df.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [146]:
raw_df.info

<bound method DataFrame.info of      symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?  alfa-romero       gas        std
3            2               164         audi       gas        std
4            2               164         audi       gas        std
..         ...               ...          ...       ...        ...
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
203         -1                95        volvo    diesel      turbo
204         -1                95        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
..           ...          ...          ...             ...         ...  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111
1            130         mpfi  3.47    2.68               9.0        111
2            152         mpfi  2.68    3.47               9.0        154
3            109         mpfi  3.19    3.40              10.0        102
4            136         mpfi  3.19    3.40               8.0        115
..           ...          ...   ...     ...               ...        ...
200          141         mpfi  3.78    3.15               9.5        114
201          141         mpfi  3.78    3.15               8.7        160
202          173         mpfi  3.58    2.87               8.8        134
203          145          idi  3.01    3.40              23.0        106
204          141         mpfi  3.78    3.15               9.5        114

     peak-rpm city-mpg highway-mpg  price
0        5000       21          27  13495
1        5000       21          27  16500
2        5000       19          26  16500
3        5500       24          30  13950
4        5500       18          22  17450
..        ...      ...         ...    ...
200      5400       23          28  16845
201      5300       19          25  19045
202      5500       18          23  21485
203      4800       26          27  22470
204      5400       19          25  22625

[205 rows x 26 columns]>

In [147]:
#Find all unique values for each col and print
print(raw_df.nunique())

symboling              6
normalized-losses     52
make                  22
fuel-type              2
aspiration             2
num-of-doors           3
body-style             5
drive-wheels           3
engine-location        2
wheel-base            53
length                75
width                 44
height                49
curb-weight          171
engine-type            7
num-of-cylinders       7
engine-size           44
fuel-system            8
bore                  39
stroke                37
compression-ratio     32
horsepower            60
peak-rpm              24
city-mpg              29
highway-mpg           30
price                187
dtype: int64

In [148]:
for col in raw_df:
  print(f"Unique values in {col}: {raw_df[col].unique()}")

Unique values in symboling: [ 3  1  2  0 -1 -2]
Unique values in normalized-losses: ['?' '164' '158' '192' '188' '121' '98' '81' '118' '148' '110' '145' '137'
 '101' '78' '106' '85' '107' '104' '113' '150' '129' '115' '93' '142'
 '161' '153' '125' '128' '122' '103' '168' '108' '194' '231' '119' '154'
 '74' '186' '83' '102' '89' '87' '77' '91' '134' '65' '197' '90' '94'
 '256' '95']
Unique values in make: ['alfa-romero' 'audi' 'bmw' 'chevrolet' 'dodge' 'honda' 'isuzu' 'jaguar'
 'mazda' 'mercedes-benz' 'mercury' 'mitsubishi' 'nissan' 'peugot'
 'plymouth' 'porsche' 'renault' 'saab' 'subaru' 'toyota' 'volkswagen'
 'volvo']
Unique values in fuel-type: ['gas' 'diesel']
Unique values in aspiration: ['std' 'turbo']
Unique values in num-of-doors: ['two' 'four' '?']
Unique values in body-style: ['convertible' 'hatchback' 'sedan' 'wagon' 'hardtop']
Unique values in drive-wheels: ['rwd' 'fwd' '4wd']
Unique values in engine-location: ['front' 'rear']
Unique values in wheel-base: [ 88.6  94.5  99.8  99.4 105.8  99.5 101.2 103.5 110.   88.4  93.7 103.3
  95.9  86.6  96.5  94.3  96.  113.  102.   93.1  95.3  98.8 104.9 106.7
 115.6  96.6 120.9 112.  102.7  93.   96.3  95.1  97.2 100.4  91.3  99.2
 107.9 114.2 108.   89.5  98.4  96.1  99.1  93.3  97.   96.9  95.7 102.4
 102.9 104.5  97.3 104.3 109.1]
Unique values in length: [168.8 171.2 176.6 177.3 192.7 178.2 176.8 189.  193.8 197.  141.1 155.9
 158.8 157.3 174.6 173.2 144.6 150.  163.4 157.1 167.5 175.4 169.1 170.7
 172.6 199.6 191.7 159.1 166.8 169.  177.8 175.  190.9 187.5 202.6 180.3
 208.1 199.2 178.4 173.  172.4 165.3 170.2 165.6 162.4 173.4 181.7 184.6
 178.5 186.7 198.9 167.3 168.9 175.7 181.5 186.6 156.9 157.9 172.  173.5
 173.6 158.7 169.7 166.3 168.7 176.2 175.6 183.5 187.8 171.7 159.3 165.7
 180.2 183.1 188.8]
Unique values in width: [64.1 65.5 66.2 66.4 66.3 71.4 67.9 64.8 66.9 70.9 60.3 63.6 63.8 64.6
 63.9 64.  65.2 62.5 66.  61.8 69.6 70.6 64.2 65.7 66.5 66.1 70.3 71.7
 70.5 72.  68.  64.4 65.4 68.4 68.3 65.  72.3 66.6 63.4 65.6 67.7 67.2
 68.9 68.8]
Unique values in height: [48.8 52.4 54.3 53.1 55.7 55.9 52.  53.7 56.3 53.2 50.8 50.6 59.8 50.2
 52.6 54.5 58.3 53.3 54.1 51.  53.5 51.4 52.8 47.8 49.6 55.5 54.4 56.5
 58.7 54.9 56.7 55.4 54.8 49.4 51.6 54.7 55.1 56.1 49.7 56.  50.5 55.2
 52.5 53.  59.1 53.9 55.6 56.2 57.5]
Unique values in curb-weight: [2548 2823 2337 2824 2507 2844 2954 3086 3053 2395 2710 2765 3055 3230
 3380 3505 1488 1874 1909 1876 2128 1967 1989 2191 2535 2811 1713 1819
 1837 1940 1956 2010 2024 2236 2289 2304 2372 2465 2293 2734 4066 3950
 1890 1900 1905 1945 1950 2380 2385 2500 2410 2443 2425 2670 2700 3515
 3750 3495 3770 3740 3685 3900 3715 2910 1918 1944 2004 2145 2370 2328
 2833 2921 2926 2365 2405 2403 1889 2017 1938 1951 2028 1971 2037 2008
 2324 2302 3095 3296 3060 3071 3139 3020 3197 3430 3075 3252 3285 3485
 3130 2818 2778 2756 2800 3366 2579 2460 2658 2695 2707 2758 2808 2847
 2050 2120 2240 2190 2340 2510 2290 2455 2420 2650 1985 2040 2015 2280
 3110 2081 2109 2275 2094 2122 2140 2169 2204 2265 2300 2540 2536 2551
 2679 2714 2975 2326 2480 2414 2458 2976 3016 3131 3151 2261 2209 2264
 2212 2319 2254 2221 2661 2563 2912 3034 2935 3042 3045 3157 2952 3049
 3012 3217 3062]
Unique values in engine-type: ['dohc' 'ohcv' 'ohc' 'l' 'rotor' 'ohcf' 'dohcv']
Unique values in num-of-cylinders: ['four' 'six' 'five' 'three' 'twelve' 'two' 'eight']
Unique values in engine-size: [130 152 109 136 131 108 164 209  61  90  98 122 156  92  79 110 111 119
 258 326  91  70  80 140 134 183 234 308 304  97 103 120 181 151 194 203
 132 121 146 171 161 141 173 145]
Unique values in fuel-system: ['mpfi' '2bbl' 'mfi' '1bbl' 'spfi' '4bbl' 'idi' 'spdi']
Unique values in bore: ['3.47' '2.68' '3.19' '3.13' '3.50' '3.31' '3.62' '2.91' '3.03' '2.97'
 '3.34' '3.60' '2.92' '3.15' '3.43' '3.63' '3.54' '3.08' '?' '3.39' '3.76'
 '3.58' '3.46' '3.80' '3.78' '3.17' '3.35' '3.59' '2.99' '3.33' '3.70'
 '3.61' '3.94' '3.74' '2.54' '3.05' '3.27' '3.24' '3.01']
Unique values in stroke: ['2.68' '3.47' '3.40' '2.80' '3.19' '3.39' '3.03' '3.11' '3.23' '3.46'
 '3.90' '3.41' '3.07' '3.58' '4.17' '2.76' '3.15' '?' '3.16' '3.64' '3.10'
 '3.35' '3.12' '3.86' '3.29' '3.27' '3.52' '2.19' '3.21' '2.90' '2.07'
 '2.36' '2.64' '3.08' '3.50' '3.54' '2.87']
Unique values in compression-ratio: [ 9.   10.    8.    8.5   8.3   7.    8.8   9.5   9.6   9.41  9.4   7.6
  9.2  10.1   9.1   8.1  11.5   8.6  22.7  22.   21.5   7.5  21.9   7.8
  8.4  21.    8.7   9.31  9.3   7.7  22.5  23.  ]
Unique values in horsepower: ['111' '154' '102' '115' '110' '140' '160' '101' '121' '182' '48' '70'
 '68' '88' '145' '58' '76' '60' '86' '100' '78' '90' '176' '262' '135'
 '84' '64' '120' '72' '123' '155' '184' '175' '116' '69' '55' '97' '152'
 '200' '95' '142' '143' '207' '288' '?' '73' '82' '94' '62' '56' '112'
 '92' '161' '156' '52' '85' '114' '162' '134' '106']
Unique values in peak-rpm: ['5000' '5500' '5800' '4250' '5400' '5100' '4800' '6000' '4750' '4650'
 '4200' '4350' '4500' '5200' '4150' '5600' '5900' '5750' '?' '5250' '4900'
 '4400' '6600' '5300']
Unique values in city-mpg: [21 19 24 18 17 16 23 20 15 47 38 37 31 49 30 27 25 13 26 36 22 14 45 28
 32 35 34 29 33]
Unique values in highway-mpg: [27 26 30 22 25 20 29 28 53 43 41 38 24 54 42 34 33 31 19 17 23 32 39 18
 16 37 50 36 47 46]
Unique values in price: ['13495' '16500' '13950' '17450' '15250' '17710' '18920' '23875' '?'
 '16430' '16925' '20970' '21105' '24565' '30760' '41315' '36880' '5151'
 '6295' '6575' '5572' '6377' '7957' '6229' '6692' '7609' '8558' '8921'
 '12964' '6479' '6855' '5399' '6529' '7129' '7295' '7895' '9095' '8845'
 '10295' '12945' '10345' '6785' '11048' '32250' '35550' '36000' '5195'
 '6095' '6795' '6695' '7395' '10945' '11845' '13645' '15645' '8495'
 '10595' '10245' '10795' '11245' '18280' '18344' '25552' '28248' '28176'
 '31600' '34184' '35056' '40960' '45400' '16503' '5389' '6189' '6669'
 '7689' '9959' '8499' '12629' '14869' '14489' '6989' '8189' '9279' '5499'
 '7099' '6649' '6849' '7349' '7299' '7799' '7499' '7999' '8249' '8949'
 '9549' '13499' '14399' '17199' '19699' '18399' '11900' '13200' '12440'
 '13860' '15580' '16900' '16695' '17075' '16630' '17950' '18150' '12764'
 '22018' '32528' '34028' '37028' '9295' '9895' '11850' '12170' '15040'
 '15510' '18620' '5118' '7053' '7603' '7126' '7775' '9960' '9233' '11259'
 '7463' '10198' '8013' '11694' '5348' '6338' '6488' '6918' '7898' '8778'
 '6938' '7198' '7788' '7738' '8358' '9258' '8058' '8238' '9298' '9538'
 '8449' '9639' '9989' '11199' '11549' '17669' '8948' '10698' '9988'
 '10898' '11248' '16558' '15998' '15690' '15750' '7975' '7995' '8195'
 '9495' '9995' '11595' '9980' '13295' '13845' '12290' '12940' '13415'
 '15985' '16515' '18420' '18950' '16845' '19045' '21485' '22470' '22625']

In [149]:
#Replace with NaN
raw_df = raw_df.replace("?",np.nan)

In [150]:
raw_df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [151]:
nan_counts = raw_df.isna().sum()
print(nan_counts)

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [152]:
for col in raw_df:
  print(f"Number of NaN in {col}: {raw_df[col].isna().sum()}")

Number of NaN in symboling: 0
Number of NaN in normalized-losses: 41
Number of NaN in make: 0
Number of NaN in fuel-type: 0
Number of NaN in aspiration: 0
Number of NaN in num-of-doors: 2
Number of NaN in body-style: 0
Number of NaN in drive-wheels: 0
Number of NaN in engine-location: 0
Number of NaN in wheel-base: 0
Number of NaN in length: 0
Number of NaN in width: 0
Number of NaN in height: 0
Number of NaN in curb-weight: 0
Number of NaN in engine-type: 0
Number of NaN in num-of-cylinders: 0
Number of NaN in engine-size: 0
Number of NaN in fuel-system: 0
Number of NaN in bore: 4
Number of NaN in stroke: 4
Number of NaN in compression-ratio: 0
Number of NaN in horsepower: 2
Number of NaN in peak-rpm: 2
Number of NaN in city-mpg: 0
Number of NaN in highway-mpg: 0
Number of NaN in price: 4

In [153]:
#find missing value percentage and decide if it can be used in the process
mis_val_percent = 100 * raw_df.isnull().sum() / len(raw_df)
print (mis_val_percent)

symboling             0.00000
normalized-losses    20.00000
make                  0.00000
fuel-type             0.00000
aspiration            0.00000
num-of-doors          0.97561
body-style            0.00000
drive-wheels          0.00000
engine-location       0.00000
wheel-base            0.00000
length                0.00000
width                 0.00000
height                0.00000
curb-weight           0.00000
engine-type           0.00000
num-of-cylinders      0.00000
engine-size           0.00000
fuel-system           0.00000
bore                  1.95122
stroke                1.95122
compression-ratio     0.00000
horsepower            0.97561
peak-rpm              0.97561
city-mpg              0.00000
highway-mpg           0.00000
price                 1.95122
dtype: float64

In [157]:
#convert object datatype to int64
#raw_df['price'] = raw_df.price.astype(int)
raw_df['price'] = pd.to_numeric(raw_df['price'], errors='coerce')
raw_df = raw_df.dropna(subset=['price'])
raw_df = raw_df.astype({'price': 'int'})

In [159]:
X=raw_df[['symboling']]
Q1 = X.quantile(0.25)
Q3 = X.quantile(0.75)
IQR = Q3 - Q1
print("Outlier threshold of Appliances ",IQR)

Outlier threshold of Appliances  symboling    2.0
dtype: float64

In [160]:
#Create a list for feature and target column
All_ColumnNames = raw_df.columns
Target_ColumnNames = ['price']
Feature_ColumnNames = ['symboling','normalized-losses', 'make', 'fuel-type', 'num-of-doors', 'body-style', 
                      'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight',
                      'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 
                       'horsepower','peak-rpm','city-mpg', 'highway-mpg']
Misc_ColumnNames = ['aspiration']

In [161]:
print(All_ColumnNames)
print(Target_ColumnNames)
print(Feature_ColumnNames)
print(Misc_ColumnNames)

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')
['price']
['symboling', 'normalized-losses', 'make', 'fuel-type', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg']
['aspiration']

In [162]:
#feature Data set
feature_df = raw_df[Feature_ColumnNames]
feature_df.head()

,symboling,normalized-losses,make,fuel-type,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg
0,3,NaN,alfa-romero,gas,two,convertible,rwd,front,88.6,168.8,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
1,3,NaN,alfa-romero,gas,two,convertible,rwd,front,88.6,168.8,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
2,1,NaN,alfa-romero,gas,two,hatchback,rwd,front,94.5,171.2,...,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26
3,2,164,audi,gas,four,sedan,fwd,front,99.8,176.6,...,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30
4,2,164,audi,gas,four,sedan,4wd,front,99.4,176.6,...,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22

In [163]:
#split raw_df data btw training and testing data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(feature_df, raw_df[Target_ColumnNames], test_size = 0.20, random_state = 0 )

In [164]:
#Feature Engineering
import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest, f_classif, RFE, VarianceThreshold

# Load the data
#df = pd.read_csv('data.csv')

# Split the data into features and target
#X = df.drop('target', axis=1)
#y = df['target']

# Remove highly correlated variables
# Set the threshold for correlation coefficient
threshold = 0.9

# Calculate the correlation matrix
corr = x_train.corr()
print(corr)
# Find the pairs of features with correlation coefficient greater than the threshold
correlated_features = np.where(corr > threshold)[0]
print("correlated_features",correlated_features)
# Remove the correlated features
#x_train = x_train.drop(correlated_features, axis=1)

# Stepwise regression
# Set the number of features to select
#k = 5
# Create a logistic regression model
model = LinearRegression()

# Perform stepwise regression

#rfe = RFE(model, k)
#rfe.fit(x_train, y_train)


from sklearn.feature_selection import SelectKBest
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import chi2, f_regression

selector = SelectKBest(f_regression, k=3)
X_new = selector.fit_transform(x_train, y_train)

# Fit a linear regression model on the selected features
model = LinearRegression()
model.fit(X_new, y_train)

# Print the coefficients of the model
print(model.coef_)
print(model.get_params())


# Get the selected features
#selected_features = rfe.support_selected_features
#X = X.iloc[:, selected_features]
#print("selected_features", selected_features)

# Remove near zero variance variables
# Set the threshold for variance
threshold = 0.01

# Calculate the variance of each feature
var = x_train.var()

# Find the features with variance less than the threshold
low_variance_features = np.where(var < threshold)[0]
print("low_variance_features", low_variance_features)
# Remove the low-variance features
#X = X.drop(low_variance_features, axis=1)

# Print the selected features
#print(x_train.columns)

                   symboling  wheel-base    length     width    height  \
symboling           1.000000   -0.543575 -0.368855 -0.251311 -0.603418
wheel-base         -0.543575    1.000000  0.870601  0.822393  0.604144
length             -0.368855    0.870601  1.000000  0.856819  0.485351
width              -0.251311    0.822393  0.856819  1.000000  0.307861
height             -0.603418    0.604144  0.485351  0.307861  1.000000
curb-weight        -0.232741    0.774199  0.879430  0.877313  0.323351
engine-size        -0.109762    0.587734  0.700520  0.753466  0.102715
compression-ratio  -0.194170    0.278372  0.175641  0.239405  0.230058
city-mpg           -0.010118   -0.506544 -0.702229 -0.651588 -0.088726
highway-mpg         0.040955   -0.559141 -0.723215 -0.699834 -0.126377

                   curb-weight  engine-size  compression-ratio  city-mpg  \
symboling            -0.232741    -0.109762          -0.194170 -0.010118
wheel-base            0.774199     0.587734           0.278372 -0.506544
length                0.879430     0.700520           0.175641 -0.702229
width                 0.877313     0.753466           0.239405 -0.651588
height                0.323351     0.102715           0.230058 -0.088726
curb-weight           1.000000     0.844075           0.217620 -0.759766
engine-size           0.844075     1.000000           0.090729 -0.639816
compression-ratio     0.217620     0.090729           1.000000  0.264732
city-mpg             -0.759766    -0.639816           0.264732  1.000000
highway-mpg          -0.796227    -0.675372           0.222290  0.977251

                   highway-mpg
symboling             0.040955
wheel-base           -0.559141
length               -0.723215
width                -0.699834
height               -0.126377
curb-weight          -0.796227
engine-size          -0.675372
compression-ratio     0.222290
city-mpg              0.977251
highway-mpg           1.000000
correlated_features [0 1 2 3 4 5 6 7 8 8 9 9]

ValueError: could not convert string to float: 'mercedes-benz'

In [94]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

num_transformer = Pipeline([
    ('num_imputer', SimpleImputer(strategy='median'))
    ])

char_transformer = Pipeline([
    ('char_imputer', SimpleImputer(strategy='most_frequent')),
    ('OHE',OneHotEncoder(handle_unknown='error',drop='first', sparse =False)),
    ])

scale_transformer = Pipeline([
    ('scaler', StandardScaler())
    ])
#OHE_transformer = OneHotEncoder(handle_unknown='error',drop='first', sparse =False)


#from sklearn.preprocessing import OneHotEncoder
#OH_encoder = OneHotEncoder(handle_unknown='error',drop='first', sparse=False)
#OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(df_train[final_char_feat_names]))
#OH_col_names = OH_encoder.get_feature_names(final_char_feat_names)
#OH_col_names

preprocessor = ColumnTransformer(
    transformers=[
         ("num", num_transformer, Feature_ColumnNames),
        ("scaler",scale_transformer,Feature_ColumnNames)
    ]
)

In [96]:
x_train

,normalized-losses,make,fuel-type,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
4,164,audi,gas,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
71,?,mercedes-benz,gas,four,sedan,rwd,front,115.6,202.6,71.7,...,234,mpfi,3.46,3.10,8.3,155,4750,16,18,34184
134,150,saab,gas,two,hatchback,fwd,front,99.1,186.6,66.5,...,121,mpfi,2.54,2.07,9.3,110,5250,21,28,15040
145,102,subaru,gas,four,sedan,4wd,front,97.0,172.0,65.4,...,108,mpfi,3.62,2.64,7.7,111,4800,24,29,11259
122,154,plymouth,gas,four,sedan,fwd,front,93.7,167.3,63.8,...,98,2bbl,2.97,3.23,9.4,68,5500,31,38,7609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,93,mercedes-benz,diesel,four,sedan,rwd,front,110.0,190.9,70.3,...,183,idi,3.58,3.64,21.5,123,4350,22,25,25552
192,?,volkswagen,diesel,four,sedan,fwd,front,100.4,180.2,66.9,...,97,idi,3.01,3.40,23.0,68,4500,33,38,13845
117,161,peugot,gas,four,sedan,rwd,front,108.0,186.7,68.3,...,134,mpfi,3.61,3.21,7.0,142,5600,18,24,18150
47,145,jaguar,gas,four,sedan,rwd,front,113.0,199.6,69.6,...,258,mpfi,3.63,4.17,8.1,176,4750,15,19,32250
172,134,toyota,gas,two,convertible,rwd,front,98.4,176.2,65.6,...,146,mpfi,3.62,3.50,9.3,116,4800,24,30,17669

In [97]:
x_test

,normalized-losses,make,fuel-type,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
52,104,mazda,gas,two,hatchback,fwd,front,93.1,159.1,64.2,...,91,2bbl,3.03,3.15,9.0,68,5000,31,38,6795
181,?,toyota,gas,four,wagon,rwd,front,104.5,187.8,66.5,...,161,mpfi,3.27,3.35,9.2,156,5200,19,24,15750
5,?,audi,gas,two,sedan,fwd,front,99.8,177.3,66.3,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
18,121,chevrolet,gas,two,hatchback,fwd,front,88.4,141.1,60.3,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
188,94,volkswagen,gas,four,sedan,fwd,front,97.3,171.7,65.5,...,109,mpfi,3.19,3.40,10.0,100,5500,26,32,9995
170,134,toyota,gas,two,hardtop,rwd,front,98.4,176.2,65.6,...,146,mpfi,3.62,3.50,9.3,116,4800,24,30,11199
76,161,mitsubishi,gas,two,hatchback,fwd,front,93.7,157.3,64.4,...,92,2bbl,2.97,3.23,9.4,68,5500,37,41,5389
154,81,toyota,gas,four,wagon,4wd,front,95.7,169.7,63.6,...,92,2bbl,3.05,3.03,9.0,62,4800,27,32,7898
104,194,nissan,gas,two,hatchback,rwd,front,91.3,170.7,67.9,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,17199
33,101,honda,gas,two,hatchback,fwd,front,93.7,150.0,64.0,...,92,1bbl,2.91,3.41,9.2,76,6000,30,34,6529
12,188,bmw,gas,two,sedan,rwd,front,101.2,176.8,64.8,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
129,?,porsche,gas,two,hatchback,rwd,front,98.4,175.7,72.3,...,203,mpfi,3.94,3.11,10.0,288,5750,17,28,?
55,150,mazda,gas,two,hatchback,rwd,front,95.3,169.0,65.7,...,70,4bbl,?,?,9.4,101,6000,17,23,10945
66,?,mazda,diesel,four,sedan,rwd,front,104.9,175.0,66.1,...,134,idi,3.43,3.64,22.0,72,4200,31,39,18344
45,?,isuzu,gas,four,sedan,fwd,front,94.5,155.9,63.6,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,?
169,134,toyota,gas,two,hatchback,rwd,front,98.4,176.2,65.6,...,146,mpfi,3.62,3.50,9.3,116,4800,24,30,9989
130,?,renault,gas,four,wagon,fwd,front,96.1,181.5,66.5,...,132,mpfi,3.46,3.90,8.7,?,?,23,31,9295
7,?,audi,gas,four,wagon,fwd,front,105.8,192.7,71.4,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
37,106,honda,gas,two,hatchback,fwd,front,96.5,167.5,65.2,...,110,1bbl,3.15,3.58,9.0,86,5800,27,33,7895
152,74,toyota,gas,four,hatchback,fwd,front,95.7,158.7,63.6,...,92,2bbl,3.05,3.03,9.0,62,4800,31,38,6488
80,153,mitsubishi,gas,two,hatchback,fwd,front,96.3,173.0,65.4,...,110,spdi,3.17,3.46,7.5,116,5500,23,30,9959
111,161,peugot,gas,four,sedan,rwd,front,107.9,186.7,68.4,...,120,mpfi,3.46,2.19,8.4,95,5000,19,24,15580
131,?,renault,gas,two,hatchback,fwd,front,96.1,176.8,66.6,...,132,mpfi,3.46,3.90,8.7,?,?,23,31,9895
171,134,toyota,gas,two,hatchback,rwd,front,98.4,176.2,65.6,...,146,mpfi,3.62,3.50,9.3,116,4800,24,30,11549
179,197,toyota,gas,two,hatchback,rwd,front,102.9,183.5,67.7,...,171,mpfi,3.27,3.35,9.3,161,5200,19,24,15998
138,83,subaru,gas,two,hatchback,fwd,front,93.7,156.9,63.4,...,97,2bbl,3.62,2.36,9.0,69,4900,31,36,5118
156,91,toyota,gas,four,sedan,fwd,front,95.7,166.3,64.4,...,98,2bbl,3.19,3.03,9.0,70,4800,30,37,6938
113,?,peugot,gas,four,wagon,rwd,front,114.2,198.9,68.4,...,120,mpfi,3.46,2.19,8.4,95,5000,19,24,16695
161,91,toyota,gas,four,hatchback,fwd,front,95.7,166.3,64.4,...,98,2bbl,3.19,3.03,9.0,70,4800,28,34,8358
89,128,nissan,gas,two,sedan,fwd,front,94.5,165.3,63.8,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,5499
183,122,volkswagen,gas,two,sedan,fwd,front,97.3,171.7,65.5,...,109,mpfi,3.19,3.40,9.0,85,5250,27,34,7975
193,?,volkswagen,gas,four,wagon,fwd,front,100.4,183.1,66.9,...,109,mpfi,3.19,3.40,9.0,88,5500,25,31,12290
125,186,porsche,gas,two,hatchback,rwd,front,94.5,168.9,68.3,...,151,mpfi,3.94,3.11,9.5,143,5500,19,27,22018
173,65,toyota,gas,four,sedan,fwd,front,102.4,175.6,66.5,...,122,mpfi,3.31,3.54,8.7,92,4200,29,34,8948
92,122,nissan,gas,four,sedan,fwd,front,94.5,165.3,63.8,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6849
16,?,bmw,gas,two,sedan,rwd,front,103.5,193.8,67.9,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315
189,?,volkswagen,gas,two,convertible,fwd,front,94.5,159.3,64.2,...,109,mpfi,3.19,3.40,8.5,90,5500,24,29,11595
136,150,saab,gas,two,hatchback,fwd,front,99.1,186.6,66.5,...,121,mpfi,3.54,3.07,9.0,160,5500,19,26,18150
22,118,dodge,gas,two,hatchback,fwd,front,93.7,157.3,63.8,...,90,2bbl,2.97,3.23,9.4,68,5500,31,38,6377
74,?,mercedes-benz,gas,two,hardtop,rwd,front,112.0,199.2,72.0,...,304,mpfi,3.80,3.35,8.0,184,4500,14,16,45400
44,?,isuzu,gas,two,sedan,fwd,front,94.5,155.9,63.6,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,?

In [99]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
# Create a logistic regression model
linreg = LinearRegression()

# Fit the model to the training data
linreg.fit(x_train, y_train)

# Predict the labels of the test data
y_pred = linreg.predict(x_test)

# Evaluate the model's performance on the test data
mse = mean_squared_error(y_test, y_pred)
print('MSE:', mse)

plt.scatter(range(len(y_test)), y_test, color='blue')
plt.scatter(range(len(y_pred)), y_pred, color='red')
plt.xlabel('Actual Values')
plt.ylabel('Predicted Values')
plt.title('Linear Regression Model')
plt.show()

ValueError: could not convert string to float: '?'